"""empty message

Revision ID: 50bc947f8115
Revises: d0ff9de1c509
Create Date: 2020-05-07 18:32:04.561749

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50bc947f8115'
down_revision = 'd0ff9de1c509'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'reviews', 'pitches', ['pitch_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reviews', type_='foreignkey')
    # ### end Alembic commands ###
